[2025-01-16T11:01:46.557+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-01-16T11:01:46.581+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL.load_data manual__2025-01-16T11:01:23.099072+00:00 [queued]>
[2025-01-16T11:01:46.588+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL.load_data manual__2025-01-16T11:01:23.099072+00:00 [queued]>
[2025-01-16T11:01:46.589+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-01-16T11:01:46.600+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): load_data> on 2025-01-16 11:01:23.099072+00:00
[2025-01-16T11:01:46.605+0000] {standard_task_runner.py:63} INFO - Started process 3489 to run task
[2025-01-16T11:01:46.607+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ETL', 'load_data', 'manual__2025-01-16T11:01:23.099072+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmp__hhtnwd']
[2025-01-16T11:01:46.609+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask load_data
[2025-01-16T11:01:46.650+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL.load_data manual__2025-01-16T11:01:23.099072+00:00 [running]> on host airflow-scheduler
[2025-01-16T11:01:46.727+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ajied(WhatsApp), Ajied(Email)' AIRFLOW_CTX_DAG_ID='ETL' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-16T11:01:23.099072+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-16T11:01:23.099072+00:00'
[2025-01-16T11:01:46.728+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-01-16T11:01:46.735+0000] {base.py:84} INFO - Using connection ID 'spark_main' for task execution.
[2025-01-16T11:01:46.736+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --jars /spark-scripts/jars/jars_postgresql-42.2.20.jar --name arrow-spark /spark-scripts/resources/load.py
[2025-01-16T11:01:48.152+0000] {spark_submit.py:641} INFO - 25/01/16 11:01:48 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-01-16T11:01:54.666+0000] {spark_submit.py:641} INFO - Traceback (most recent call last):
[2025-01-16T11:01:54.667+0000] {spark_submit.py:641} INFO - File "/spark-scripts/resources/load.py", line 75, in <module>
[2025-01-16T11:01:54.667+0000] {spark_submit.py:641} INFO - load()
[2025-01-16T11:01:54.667+0000] {spark_submit.py:641} INFO - File "/spark-scripts/resources/load.py", line 54, in load
[2025-01-16T11:01:54.668+0000] {spark_submit.py:641} INFO - transactions = pl.read_database(transactions_query, jdbc_url)
[2025-01-16T11:01:54.668+0000] {spark_submit.py:641} INFO - File "/home/airflow/.local/lib/python3.10/site-packages/polars/io/database.py", line 93, in read_database
[2025-01-16T11:01:54.669+0000] {spark_submit.py:641} INFO - return _read_sql_connectorx(
[2025-01-16T11:01:54.669+0000] {spark_submit.py:641} INFO - File "/home/airflow/.local/lib/python3.10/site-packages/polars/io/database.py", line 124, in _read_sql_connectorx
[2025-01-16T11:01:54.669+0000] {spark_submit.py:641} INFO - tbl = cx.read_sql(
[2025-01-16T11:01:54.670+0000] {spark_submit.py:641} INFO - File "/home/airflow/.local/lib/python3.10/site-packages/connectorx/__init__.py", line 389, in read_sql
[2025-01-16T11:01:54.670+0000] {spark_submit.py:641} INFO - result = _read_sql(
[2025-01-16T11:01:54.670+0000] {spark_submit.py:641} INFO - RuntimeError: db error: ERROR: relation "public.transactions" does not exist
[2025-01-16T11:01:55.003+0000] {spark_submit.py:641} INFO - 25/01/16 11:01:55 INFO ShutdownHookManager: Shutdown hook called
[2025-01-16T11:01:55.004+0000] {spark_submit.py:641} INFO - 25/01/16 11:01:55 INFO ShutdownHookManager: Deleting directory /tmp/spark-4972022a-242a-4ef7-b0b9-87110f140e59
[2025-01-16T11:01:55.059+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-01-16T11:01:55.073+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --jars /spark-scripts/jars/jars_postgresql-42.2.20.jar --name arrow-spark /spark-scripts/resources/load.py. Error code is: 1.
[2025-01-16T11:01:55.082+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ETL, task_id=load_data, run_id=manual__2025-01-16T11:01:23.099072+00:00, execution_date=20250116T110123, start_date=20250116T110146, end_date=20250116T110155
[2025-01-16T11:01:55.104+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 10 for task load_data (Cannot execute: spark-submit --master spark://spark-master:7077 --jars /spark-scripts/jars/jars_postgresql-42.2.20.jar --name arrow-spark /spark-scripts/resources/load.py. Error code is: 1.; 3489)
[2025-01-16T11:01:55.114+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-01-16T11:01:55.155+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-16T11:01:55.163+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
