[2025-01-15T15:25:09.961+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-01-15T15:25:10.095+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Data_Ingestions_transactions.spark_submit_task manual__2025-01-15T15:25:08.154428+00:00 [queued]>
[2025-01-15T15:25:10.110+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Data_Ingestions_transactions.spark_submit_task manual__2025-01-15T15:25:08.154428+00:00 [queued]>
[2025-01-15T15:25:10.111+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-01-15T15:25:10.131+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): spark_submit_task> on 2025-01-15 15:25:08.154428+00:00
[2025-01-15T15:25:10.140+0000] {standard_task_runner.py:63} INFO - Started process 255 to run task
[2025-01-15T15:25:10.144+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'Data_Ingestions_transactions', 'spark_submit_task', 'manual__2025-01-15T15:25:08.154428+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/Data_Ingestions_transactions.py', '--cfg-path', '/tmp/tmpkadq16sk']
[2025-01-15T15:25:10.148+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask spark_submit_task
[2025-01-15T15:25:10.222+0000] {task_command.py:426} INFO - Running <TaskInstance: Data_Ingestions_transactions.spark_submit_task manual__2025-01-15T15:25:08.154428+00:00 [running]> on host airflow-scheduler
[2025-01-15T15:25:10.358+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ajied(WhatsApp), Ajied(Email)' AIRFLOW_CTX_DAG_ID='Data_Ingestions_transactions' AIRFLOW_CTX_TASK_ID='spark_submit_task' AIRFLOW_CTX_EXECUTION_DATE='2025-01-15T15:25:08.154428+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-15T15:25:08.154428+00:00'
[2025-01-15T15:25:10.359+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-01-15T15:25:10.379+0000] {base.py:84} INFO - Using connection ID 'spark_main' for task execution.
[2025-01-15T15:25:10.381+0000] {spark_submit.py:474} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --jars /spark-scripts/jars/jars_postgresql-42.2.20.jar --name arrow-spark /spark-scripts/data_ingestion_transactions.py
[2025-01-15T15:25:13.902+0000] {spark_submit.py:641} INFO - 25/01/15 15:25:13 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-01-15T15:25:15.645+0000] {spark_submit.py:641} INFO - Traceback (most recent call last):
[2025-01-15T15:25:15.646+0000] {spark_submit.py:641} INFO - File "/spark-scripts/data_ingestion_transactions.py", line 19, in <module>
[2025-01-15T15:25:15.649+0000] {spark_submit.py:641} INFO - .appName("Data Ingestion")
[2025-01-15T15:25:15.650+0000] {spark_submit.py:641} INFO - AttributeError: 'SparkConf' object has no attribute 'appName'
[2025-01-15T15:25:15.709+0000] {spark_submit.py:641} INFO - 25/01/15 15:25:15 INFO ShutdownHookManager: Shutdown hook called
[2025-01-15T15:25:15.710+0000] {spark_submit.py:641} INFO - 25/01/15 15:25:15 INFO ShutdownHookManager: Deleting directory /tmp/spark-7c386670-9887-4975-af12-d846d53a8956
[2025-01-15T15:25:15.761+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-01-15T15:25:15.774+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 177, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 567, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --jars /spark-scripts/jars/jars_postgresql-42.2.20.jar --name arrow-spark /spark-scripts/data_ingestion_transactions.py. Error code is: 1.
[2025-01-15T15:25:15.783+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=Data_Ingestions_transactions, task_id=spark_submit_task, run_id=manual__2025-01-15T15:25:08.154428+00:00, execution_date=20250115T152508, start_date=20250115T152510, end_date=20250115T152515
[2025-01-15T15:25:15.803+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 2 for task spark_submit_task (Cannot execute: spark-submit --master spark://spark-master:7077 --jars /spark-scripts/jars/jars_postgresql-42.2.20.jar --name arrow-spark /spark-scripts/data_ingestion_transactions.py. Error code is: 1.; 255)
[2025-01-15T15:25:15.845+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-01-15T15:25:15.871+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-15T15:25:15.878+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
