[2025-01-17T06:54:05.732+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-01-17T06:54:05.826+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL.load_data manual__2025-01-17T06:53:32.320107+00:00 [queued]>
[2025-01-17T06:54:05.861+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL.load_data manual__2025-01-17T06:53:32.320107+00:00 [queued]>
[2025-01-17T06:54:05.864+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-01-17T06:54:05.918+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): load_data> on 2025-01-17 06:53:32.320107+00:00
[2025-01-17T06:54:05.930+0000] {standard_task_runner.py:63} INFO - Started process 4851 to run task
[2025-01-17T06:54:05.941+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ETL', 'load_data', 'manual__2025-01-17T06:53:32.320107+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmp8jj972uq']
[2025-01-17T06:54:05.949+0000] {standard_task_runner.py:91} INFO - Job 123: Subtask load_data
[2025-01-17T06:54:06.113+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL.load_data manual__2025-01-17T06:53:32.320107+00:00 [running]> on host airflow-scheduler
[2025-01-17T06:54:06.460+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ajied(WhatsApp), Ajied(Email)' AIRFLOW_CTX_DAG_ID='ETL' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-17T06:53:32.320107+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-17T06:53:32.320107+00:00'
[2025-01-17T06:54:06.464+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-01-17T06:54:06.468+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-17T06:54:06.471+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /spark-scripts/resources/load.py']
[2025-01-17T06:54:06.497+0000] {subprocess.py:86} INFO - Output:
[2025-01-17T06:54:18.799+0000] {subprocess.py:93} INFO - Terjadi error saat menulis ke BigQuery: 400 Error while reading data, error message: Parquet column 'sale_date' has type INT64 which does not match the target cpp_type INT32.; reason: invalid, message: Error while reading data, error message: Parquet column 'sale_date' has type INT64 which does not match the target cpp_type INT32.
[2025-01-17T06:54:19.140+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-01-17T06:54:19.142+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-01-17T06:54:19.180+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ETL, task_id=load_data, run_id=manual__2025-01-17T06:53:32.320107+00:00, execution_date=20250117T065332, start_date=20250117T065405, end_date=20250117T065419
[2025-01-17T06:54:19.229+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-01-17T06:54:19.293+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-17T06:54:19.300+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
