[2025-01-17T06:45:35.303+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-01-17T06:45:35.370+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL.load_data manual__2025-01-17T06:44:59.708568+00:00 [queued]>
[2025-01-17T06:45:35.388+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL.load_data manual__2025-01-17T06:44:59.708568+00:00 [queued]>
[2025-01-17T06:45:35.389+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-01-17T06:45:35.416+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): load_data> on 2025-01-17 06:44:59.708568+00:00
[2025-01-17T06:45:35.423+0000] {standard_task_runner.py:63} INFO - Started process 3722 to run task
[2025-01-17T06:45:35.429+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ETL', 'load_data', 'manual__2025-01-17T06:44:59.708568+00:00', '--job-id', '117', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmpc_iw8z47']
[2025-01-17T06:45:35.433+0000] {standard_task_runner.py:91} INFO - Job 117: Subtask load_data
[2025-01-17T06:45:35.521+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL.load_data manual__2025-01-17T06:44:59.708568+00:00 [running]> on host airflow-scheduler
[2025-01-17T06:45:35.689+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ajied(WhatsApp), Ajied(Email)' AIRFLOW_CTX_DAG_ID='ETL' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-17T06:44:59.708568+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-17T06:44:59.708568+00:00'
[2025-01-17T06:45:35.692+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-01-17T06:45:35.693+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-17T06:45:35.695+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /spark-scripts/resources/load.py']
[2025-01-17T06:45:35.709+0000] {subprocess.py:86} INFO - Output:
[2025-01-17T06:45:50.132+0000] {subprocess.py:93} INFO - Terjadi error saat menulis ke BigQuery: 400 Error while reading data, error message: Parquet column 'sale_date' has type INT64 which does not match the target cpp_type INT32.; reason: invalid, message: Error while reading data, error message: Parquet column 'sale_date' has type INT64 which does not match the target cpp_type INT32.
[2025-01-17T06:45:50.434+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-01-17T06:45:50.435+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-01-17T06:45:50.473+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ETL, task_id=load_data, run_id=manual__2025-01-17T06:44:59.708568+00:00, execution_date=20250117T064459, start_date=20250117T064535, end_date=20250117T064550
[2025-01-17T06:45:50.510+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-01-17T06:45:50.531+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-17T06:45:50.535+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
