[2025-01-16T11:16:32.911+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-01-16T11:16:32.933+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ETL.load_data manual__2025-01-16T11:16:13.527865+00:00 [queued]>
[2025-01-16T11:16:32.939+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ETL.load_data manual__2025-01-16T11:16:13.527865+00:00 [queued]>
[2025-01-16T11:16:32.940+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-01-16T11:16:32.952+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): load_data> on 2025-01-16 11:16:13.527865+00:00
[2025-01-16T11:16:32.956+0000] {standard_task_runner.py:63} INFO - Started process 5789 to run task
[2025-01-16T11:16:32.958+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ETL', 'load_data', 'manual__2025-01-16T11:16:13.527865+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/ETL.py', '--cfg-path', '/tmp/tmpt_wr56kb']
[2025-01-16T11:16:32.960+0000] {standard_task_runner.py:91} INFO - Job 22: Subtask load_data
[2025-01-16T11:16:33.006+0000] {task_command.py:426} INFO - Running <TaskInstance: ETL.load_data manual__2025-01-16T11:16:13.527865+00:00 [running]> on host airflow-scheduler
[2025-01-16T11:16:33.088+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ajied(WhatsApp), Ajied(Email)' AIRFLOW_CTX_DAG_ID='ETL' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2025-01-16T11:16:13.527865+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-16T11:16:13.527865+00:00'
[2025-01-16T11:16:33.089+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-01-16T11:16:33.090+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-01-16T11:16:33.091+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /spark-scripts/resources/load.py']
[2025-01-16T11:16:33.098+0000] {subprocess.py:86} INFO - Output:
[2025-01-16T11:16:45.239+0000] {subprocess.py:93} INFO - Terjadi error saat menulis ke BigQuery: 400 Error while reading data, error message: Parquet column 'quantity' has type DOUBLE which does not match the target cpp_type INT64.; reason: invalid, message: Error while reading data, error message: Parquet column 'quantity' has type DOUBLE which does not match the target cpp_type INT64.
[2025-01-16T11:16:45.411+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-01-16T11:16:45.412+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-01-16T11:16:45.443+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ETL, task_id=load_data, run_id=manual__2025-01-16T11:16:13.527865+00:00, execution_date=20250116T111613, start_date=20250116T111632, end_date=20250116T111645
[2025-01-16T11:16:45.497+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-01-16T11:16:45.533+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-16T11:16:45.537+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
